### ISSUE TITLE
Update to reflect latest Primo point releases

### ISSUE THREAD

**Issue by erinrwhite** [vculibraries/alma-primo-customizations#3]
Need to update the CSS and JS files to reflect our newest changes

**Comment by alitinker** [comment]
I'm guessing I can leave out the Qatar changes...

**Comment by erinrwhite** [comment]
ya! thanks.

**Comment by alitinker** [comment]
I left out Adwords and Qatar changes. I think everything else is accounted for.

**Comment by erinrwhite** [comment]
many thanks!​
